// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MESSAGES_NIGHTPROTOCOL_H_
#define FLATBUFFERS_GENERATED_MESSAGES_NIGHTPROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace NightProtocol {

struct ChatMessage;
struct ChatMessageBuilder;

struct Vec2;

struct MoveRequest;
struct MoveRequestBuilder;

struct StateSync;
struct StateSyncBuilder;

struct Message;
struct MessageBuilder;

enum class MessagePayload : uint8_t {
  NONE = 0,
  ChatMessage = 1,
  MoveRequest = 2,
  StateSync = 3,
  MIN = NONE,
  MAX = StateSync
};

inline const MessagePayload (&EnumValuesMessagePayload())[4] {
  static const MessagePayload values[] = {
    MessagePayload::NONE,
    MessagePayload::ChatMessage,
    MessagePayload::MoveRequest,
    MessagePayload::StateSync
  };
  return values;
}

inline const char * const *EnumNamesMessagePayload() {
  static const char * const names[5] = {
    "NONE",
    "ChatMessage",
    "MoveRequest",
    "StateSync",
    nullptr
  };
  return names;
}

inline const char *EnumNameMessagePayload(MessagePayload e) {
  if (::flatbuffers::IsOutRange(e, MessagePayload::NONE, MessagePayload::StateSync)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMessagePayload()[index];
}

template<typename T> struct MessagePayloadTraits {
  static const MessagePayload enum_value = MessagePayload::NONE;
};

template<> struct MessagePayloadTraits<NightProtocol::ChatMessage> {
  static const MessagePayload enum_value = MessagePayload::ChatMessage;
};

template<> struct MessagePayloadTraits<NightProtocol::MoveRequest> {
  static const MessagePayload enum_value = MessagePayload::MoveRequest;
};

template<> struct MessagePayloadTraits<NightProtocol::StateSync> {
  static const MessagePayload enum_value = MessagePayload::StateSync;
};

template <bool B = false>
bool VerifyMessagePayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, MessagePayload type);
template <bool B = false>
bool VerifyMessagePayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<MessagePayload> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec2 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  Vec2()
      : x_(0),
        y_(0) {
  }
  Vec2(float _x, float _y)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Vec2, 8);

struct ChatMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ChatMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONTENT = 4
  };
  const ::flatbuffers::String *content() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONTENT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CONTENT) &&
           verifier.VerifyString(content()) &&
           verifier.EndTable();
  }
};

struct ChatMessageBuilder {
  typedef ChatMessage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_content(::flatbuffers::Offset<::flatbuffers::String> content) {
    fbb_.AddOffset(ChatMessage::VT_CONTENT, content);
  }
  explicit ChatMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ChatMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ChatMessage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ChatMessage> CreateChatMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> content = 0) {
  ChatMessageBuilder builder_(_fbb);
  builder_.add_content(content);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ChatMessage> CreateChatMessageDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *content = nullptr) {
  auto content__ = content ? _fbb.CreateString(content) : 0;
  return NightProtocol::CreateChatMessage(
      _fbb,
      content__);
}

struct MoveRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MoveRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITION = 4
  };
  const NightProtocol::Vec2 *position() const {
    return GetStruct<const NightProtocol::Vec2 *>(VT_POSITION);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<NightProtocol::Vec2>(verifier, VT_POSITION, 4) &&
           verifier.EndTable();
  }
};

struct MoveRequestBuilder {
  typedef MoveRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_position(const NightProtocol::Vec2 *position) {
    fbb_.AddStruct(MoveRequest::VT_POSITION, position);
  }
  explicit MoveRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MoveRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MoveRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MoveRequest> CreateMoveRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const NightProtocol::Vec2 *position = nullptr) {
  MoveRequestBuilder builder_(_fbb);
  builder_.add_position(position);
  return builder_.Finish();
}

struct StateSync FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StateSyncBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SESSION_ID = 4,
    VT_POSITION = 6
  };
  uint32_t session_id() const {
    return GetField<uint32_t>(VT_SESSION_ID, 0);
  }
  const NightProtocol::Vec2 *position() const {
    return GetStruct<const NightProtocol::Vec2 *>(VT_POSITION);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SESSION_ID, 4) &&
           VerifyField<NightProtocol::Vec2>(verifier, VT_POSITION, 4) &&
           verifier.EndTable();
  }
};

struct StateSyncBuilder {
  typedef StateSync Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_session_id(uint32_t session_id) {
    fbb_.AddElement<uint32_t>(StateSync::VT_SESSION_ID, session_id, 0);
  }
  void add_position(const NightProtocol::Vec2 *position) {
    fbb_.AddStruct(StateSync::VT_POSITION, position);
  }
  explicit StateSyncBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StateSync> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StateSync>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StateSync> CreateStateSync(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t session_id = 0,
    const NightProtocol::Vec2 *position = nullptr) {
  StateSyncBuilder builder_(_fbb);
  builder_.add_position(position);
  builder_.add_session_id(session_id);
  return builder_.Finish();
}

struct Message FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  NightProtocol::MessagePayload payload_type() const {
    return static_cast<NightProtocol::MessagePayload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const NightProtocol::ChatMessage *payload_as_ChatMessage() const {
    return payload_type() == NightProtocol::MessagePayload::ChatMessage ? static_cast<const NightProtocol::ChatMessage *>(payload()) : nullptr;
  }
  const NightProtocol::MoveRequest *payload_as_MoveRequest() const {
    return payload_type() == NightProtocol::MessagePayload::MoveRequest ? static_cast<const NightProtocol::MoveRequest *>(payload()) : nullptr;
  }
  const NightProtocol::StateSync *payload_as_StateSync() const {
    return payload_type() == NightProtocol::MessagePayload::StateSync ? static_cast<const NightProtocol::StateSync *>(payload()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyMessagePayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const NightProtocol::ChatMessage *Message::payload_as<NightProtocol::ChatMessage>() const {
  return payload_as_ChatMessage();
}

template<> inline const NightProtocol::MoveRequest *Message::payload_as<NightProtocol::MoveRequest>() const {
  return payload_as_MoveRequest();
}

template<> inline const NightProtocol::StateSync *Message::payload_as<NightProtocol::StateSync>() const {
  return payload_as_StateSync();
}

struct MessageBuilder {
  typedef Message Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(NightProtocol::MessagePayload payload_type) {
    fbb_.AddElement<uint8_t>(Message::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(Message::VT_PAYLOAD, payload);
  }
  explicit MessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Message>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Message> CreateMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    NightProtocol::MessagePayload payload_type = NightProtocol::MessagePayload::NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  MessageBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

template <bool B>
inline bool VerifyMessagePayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, MessagePayload type) {
  switch (type) {
    case MessagePayload::NONE: {
      return true;
    }
    case MessagePayload::ChatMessage: {
      auto ptr = reinterpret_cast<const NightProtocol::ChatMessage *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessagePayload::MoveRequest: {
      auto ptr = reinterpret_cast<const NightProtocol::MoveRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessagePayload::StateSync: {
      auto ptr = reinterpret_cast<const NightProtocol::StateSync *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyMessagePayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<MessagePayload> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyMessagePayload(
        verifier,  values->Get(i), types->GetEnum<MessagePayload>(i))) {
      return false;
    }
  }
  return true;
}

inline const NightProtocol::Message *GetMessage(const void *buf) {
  return ::flatbuffers::GetRoot<NightProtocol::Message>(buf);
}

inline const NightProtocol::Message *GetSizePrefixedMessage(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<NightProtocol::Message>(buf);
}

template <bool B = false>
inline bool VerifyMessageBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<NightProtocol::Message>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedMessageBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<NightProtocol::Message>(nullptr);
}

inline void FinishMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<NightProtocol::Message> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<NightProtocol::Message> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace NightProtocol

#endif  // FLATBUFFERS_GENERATED_MESSAGES_NIGHTPROTOCOL_H_
